### PR TITLE
Fix DiscontinuousMaterialProperty

### LINKED ISSUE #199: Test all material_proprety options
Currently, the solver doesn't converge for `discontinuous`, but gives similar results for `constant`, `linear` and `linear_x`. We should make sure that all options actually work.

### PR DESCRIPTION
**Pull request by masterleinad**
This change makes sure that we are indeed using the same coefficients for the matrix-free and the matrix-based case. Fixes #199.

### CODE REVIEW

File: tests/test_hierarchy_helpers.hpp [hunk 1]
```diff
@@ -155,11 +155,19 @@ class DiscontinuousMaterialProperty final : public Coefficient<dim>
...
+    for (unsigned int i = 0;
+         i < dealii::VectorizedArray<double>::n_array_elements; ++i)
+      for (unsigned int d = 0; d < dim; ++d)
+        dim_scale[i] +=
+            static_cast<unsigned int>(std::floor(100. * p[d][i])) % 2;
+
+    dealii::VectorizedArray<double> return_value;
+    for (unsigned int i = 0;
+         i < dealii::VectorizedArray<double>::n_array_elements; ++i)
+      return_value[i] = (dim_scale[i] == dim ? 100. : 10.);
```
Comment (Rombur) [inline tests/test_hierarchy_helpers.hpp]: Can you assign a `double` to a `VectorizedArray`?

**Review by Rombur — COMMENTED** [review]
It looks OK but it doesn't compile on jenkins (`one` is not used).

File: tests/test_hierarchy_helpers.hpp (hunk 1 above)
Comment (masterleinad) [reply tests/test_hierarchy_helpers.hpp]: Yes, https://www.dealii.org/current/doxygen/deal.II/classVectorizedArray.html#a2a6e8e58f020c57afc202b17f93c0774, but that is not what I am doing.

File: tests/test_hierarchy.cc [hunk 2]
```diff
@@ -597,3 +597,65 @@ BOOST_AUTO_TEST_CASE(fast_multiply_transpose_mf)
...
 }
+
+template <int dim>
+class ConstantMaterialProperty;
+template <int dim>
+class LinearMaterialProperty;
+template <int dim>
+class LinearXMaterialProperty;
+template <int dim>
+class DiscontinuousMaterialProperty;
```
Comment (dalg24) [inline tests/test_hierarchy.cc]: Why did you add these declarations?  Aren't they already available in the header `test_hierarchy_helpers.hpp`?

File: tests/test_hierarchy.cc [hunk 3]
```diff
@@ -597,3 +597,65 @@ BOOST_AUTO_TEST_CASE(fast_multiply_transpose_mf)
...
+               LinearXMaterialProperty<2>, DiscontinuousMaterialProperty<2>>;
+BOOST_AUTO_TEST_CASE_TEMPLATE(test_material_properties, MaterialProperty,
+                              material_properties)
+{
+  dealii::MultithreadInfo::set_thread_limit(1);
+
+  MPI_Comm comm = MPI_COMM_WORLD;
+
+  using DVector = dealii::LinearAlgebra::distributed::Vector<double>;
+  int constexpr dim = mfmg::DealIIMatrixFreeMeshEvaluator<2>::_dim;
```
Comment (dalg24) [inline tests/test_hierarchy.cc]: ??

File: tests/test_hierarchy.cc (hunk 2 above)
Comment (masterleinad) [reply tests/test_hierarchy.cc]: Ah, yes they made debugging easier. I'll remove them.

File: tests/test_hierarchy.cc (hunk 3 above)
Comment (masterleinad) [reply tests/test_hierarchy.cc]: We do that all over the place in this test.

Comment (dalg24) [reply tests/test_hierarchy.cc]: I see two other offenders: https://github.com/ORNL-CEES/mfmg/blob/93e4253727b92d7dbc3d4dd7c743bbaf6c70a9c9/tests/test_hierarchy.cc#L472 and https://github.com/ORNL-CEES/mfmg/blob/93e4253727b92d7dbc3d4dd7c743bbaf6c70a9c9/tests/test_hierarchy.cc#L540

Please change to `int constexpr dim = <DIM>;` and let's merge

**Review by dalg24 — APPROVED** [review]
